#!/bin/bash
#set -x

TMPFILE=
SOURCE=/sys/kernel/security/tpm0/ascii_bios_measurements

cleanup()
{
	rm -f $TMPFILE
}

PCR=${1:??}

AWK_STR="\$1 ~ /${PCR}/ { print \$2 }"
MEASUREMENTS=$(cat $SOURCE | awk "$AWK_STR")

TMPFILE=$(mktemp -q /tmp/${0##*/}-XXXXXX)

if [ ! -n "$TMPFILE" ]; then
	echo "Temp file creation failed"
	exit -1
else
	trap cleanup EXIT
fi

i=1
m_elems=( $MEASUREMENTS )
for m in $MEASUREMENTS; do
	if [ $i -eq 1 ]; then
		if [ ${#m_elems[*]} -eq $i ]; then
			calc_pcr -o $TMPFILE -h $m
		else
			calc_pcr -o $TMPFILE -h $m >/dev/null
		fi
	else
		if [ ${#m_elems[*]} -eq $i ]; then
			calc_pcr -f $TMPFILE -o $TMPFILE -h $m
		else
			calc_pcr -f $TMPFILE -o $TMPFILE -h $m >/dev/null
		fi
	fi

	i=$(( $i + 1 ))
done
