#!/bin/bash
#
# Enable and take ownership of the TPM, then
#
if [ ! -e /sys/class/misc/tpm0/device/enabled ]; then
	echo "Your TPM device driver doesn't appear to be loaded. Please run"
	echo "\`modprobe tpm_tis\` to load the driver and re-run this script"
	exit -1
fi

if [ ! /sys/class/misc/tpm0/device/enabled ]; then
	echo "Your TPM is not enabled in your BIOS. Please halt the machine and"
	echo "then cold boot into your BIOS to enable the TPM chip."
	exit -1
fi

if [ ! /sys/class/misc/tpm0/device/owned ]; then
	echo "Your TPM is unowned, please take ownership:"
	tpm_takeownership || exit -1
fi

KEY_FILE=$(tpm_nvram_data_mover create)



cryptsetup luksAddKey

exit 0
