#!/bin/bash

if grep -q nash /usr/libexec/plymouth/plymouth-populate-initrd \
   || ! grep -q PLYMOUTH_POPULATE_SOURCE_FUNCTIONS /usr/libexec/plymouth/plymouth-populate-initrd \
   || [ ! -x /usr/libexec/plymouth/plymouth-populate-initrd ]; then
    . "$moddir"/plymouth-populate-initrd
else
    PLYMOUTH_POPULATE_SOURCE_FUNCTIONS="$dracutfunctions" \
        /usr/libexec/plymouth/plymouth-populate-initrd -t $initdir
fi

inst_hook pre-pivot 90 "$moddir"/plymouth-newroot.sh
inst_hook pre-trigger 10 "$moddir"/plymouth-pretrigger.sh
inst_hook emergency 00 "$moddir"/plymouth-emergency.sh
inst "$moddir"/cryptroot-ask.sh /sbin/cryptroot-ask
inst "$moddir"/cryptroot-ask-tpm.sh /sbin/cryptroot-ask-tpm
inst readlink
