#!/bin/bash -e
#set -x
TMPDIR=$(mktemp -d /tmp/${0##*/}-XXXXXX)

if [ ! -d ${TMPDIR} ]; then
	echo "Temp directory creation failed. Check why this might have failed and re-reun tpm-luks-update"
	exit 255
fi

function cleanup
{
	rm -rf ${TMPDIR}
}

trap cleanup EXIT

# generate new PCR values based off the new kernel/initramfs binaries
tpm-luks-gen-pcr-values -d ${TMPDIR} || exit -1
if [ $? -ne 0 ]; then
	echo "tpm-luks-gen-pcr-values has failed. Aborting. Is securityfs mounted?"
	echo "The file /sys/kernel/security/tpm0/ascii_bios_measurements should exist and be readable."
	exit 255
fi

tpm-luks -m -p ${TMPDIR}/nv-perms-boot-entry-0.txt

exit $?
