#!/bin/bash -e
#
# tpm-luks-update: calculate new PCR values and migrate a TPM NVRAM
#		   area to be sealed to them. Should be called automatically
#		   by
#
#
#set -x
TMPDIR=$(mktemp -d /tmp/${0##*/}-XXXXXX)

if [ ! -d ${TMPDIR} ]; then
	echo "Temp directory creation failed. Check why this might have failed and re-reun tpm-luks-update"
	exit 255
fi

function cleanup
{
	rm -rf ${TMPDIR}
}

trap cleanup EXIT

# generate new PCR values based off the new kernel/initramfs binaries
tpm-luks-gen-tgrub-pcr-values -d ${TMPDIR}
if [ $? -ne 0 ]; then
	echo "tpm-luks-gen-tgrub-pcr-values has failed. Aborting. Is securityfs mounted?"
	echo "The file /sys/kernel/security/tpm0/ascii_bios_measurements should exist and be readable."
	exit 255
fi

if [ -e ${TMPDIR}/nv-perms-boot-entry-0.txt ]; then
	tpm-luks -m -p ${TMPDIR}/nv-perms-boot-entry-0.txt
fi

exit $?
