#!/bin/bash -e
set -x
DRACUT=/sbin/dracut
UTILS="$(which od) $(which awk) $(which getcapability) $(which nv_readvalue)"
TMPDIR=$(mktemp -d /tmp/${0##*/}-XXXXXX)
KERNEL=$(grubby --default-kernel)
INITRAMFS="${KERNEL//vmlinuz/initramfs}-tpm-luks.img"
TITLE='Linux (TPM LUKS) test'

function cleanup
{
	rm -rf ${TMPDIR}
}

trap cleanup EXIT

grubby --copy-default --title "${TITLE}" --add-kernel=${KERNEL} --initrd=${INITRAMFS}

# copy the utilities we need for dracut into a tmp dir
cp -a ${UTILS} ${TMPDIR}

# create a new initramfs based on the newly installed one. We're not
# overwriting an old initramfs here, so --force isn't needed
$DRACUT -a plymouth-tpm -o plymouth -i ${TMPDIR} /usr/bin ${INITRAMFS}

# generate new PCR values based off the new kernel/initramfs binaries
gen_pcr_values -d ${TMPDIR} || exit -1

# grubby adds us at the top, so we'll migrate based on the PCRs produced
# for menu.lst entry 0
tpm_luks -m -p ${TMPDIR}/nv-perms-boot-entry-0.txt

exit $?
